version: "3.9"

services:
  web:
    build: ./backend
    ports:
      - "5555:5000"     # 本机 localhost:5555 ↔ 容器内 5000

  frontend:
    build: ./frontend
    ports:
      - "3333:3000"     # 本机 localhost:3333 ↔ 容器内 3000
    environment:
      # 在容器内用服务名 web 来访问后端
      - REACT_APP_BACKEND_URL=http://web:5000
      - NODE_OPTIONS=--openssl-legacy-provider 
    depends_on:
      - web
